nelmio_api_doc:
    documentation:
        info:
            title: HomeCyclHome
            description: Documentation de l’API HomeCyclHome, réparation et entretien de vélo à domicile
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
