services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homecyclhome_api-app
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      APP_ENV: prod
      APP_RUNTIME: "Runtime\\FrankenPhpSymfony\\Runtime"
      DATABASE_URL: postgres://symfony:symfony@db:5432/symfony
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend

  db:
    image: postgres:17.5-bookworm
    container_name: homecyclhome_api-db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: homecyclhome_api-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: andre.raphael@ik.me
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend


volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  backend:
