name: Deploy API (TEST - auto)

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - "compose.yaml"
      - ".github/workflows/deploy-test.yml"

jobs:
  deploy-test:
    name: Build on VPS & restart (TEST)
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy-test
      cancel-in-progress: false

    steps:
      - name: SSH & deploy (TEST)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -e

            # Dossier test
            cd /var/www/homecyclhome_test/homecyclhome_API

            docker ps >/dev/null

            git config --global --add safe.directory /var/www/homecyclhome_test/homecyclhome_API
            git fetch origin main
            git reset --hard origin/main

            # En cas de 1er run
            docker compose -p homecyclhome_api_test up -d db pgadmin

            # Build+up uniquement le service app (db/pgadmin restent inchangés si déjà créés)
            DOCKER_BUILDKIT=1 docker compose -p homecyclhome_api_test build --pull app
            docker compose -p homecyclhome_api_test up -d --no-deps app

            # nettoyage images non utilisées
            docker image prune -f

            docker compose -p homecyclhome_api_test ps
            docker compose -p homecyclhome_api_test logs --since=1m app || true
