name: Deploy API (PROD - manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build on VPS & restart app
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy-production
      cancel-in-progress: false

    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            # Dossier prod
            cd /var/www/homecyclhome/homecyclhome_API

            docker ps >/dev/null

            git fetch origin main
            git reset --hard origin/main

            DOCKER_BUILDKIT=1 docker compose build --pull app
            docker compose up -d --no-deps app

            docker image prune -f

            docker compose ps
            docker compose logs --since=1m app || true

            # docker compose exec -T app php bin/console doctrine:migrations:migrate --no-interaction
